# Generated by Django 3.2 on 2023-12-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='Название',
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default=2, max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
