# Generated by Django 3.2 on 2023-12-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231212_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(to='api.Genre', verbose_name='Жанр'),
        ),
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
